---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "42"
year: "2022"
contributor: 
- Karsten Schuldt
title: "Die nationalen Bibliothekswesen sind stark auf sich selbst bezogen: Eine Auswertung der bibliothekarischen Zeitschriften im DACH-Raum mit Bezug auf internationale Themen"
abstract: "Ausgewertet werden hier Daten einer Vollerhebung der Texte, welche in bibliothekarischen Zeitschriften des DACH-Raumes in den Jahren 2001, 2011 und 2021 erschienen sind, daraufhin, in welchen Sprachen und zu welchen internationalen Themen in diesen publiziert wird sowie, aus welchen L채ndern die jeweiligen Autor*innen stammten. Es zeigt sich, dass die bibliothekarischen Zeitschriften im DACH-Raum fast durchg채ngig in Deutsch publizieren und kaum Themen aus den Bibliothekswesen eines anderen Landes publizieren. Grunds채tzlich gibt es sogar einen R체ckgang der internationalen Themen, sowohl von ausserhalb des DACH-Raumes als auch innerhalb dieses."
pdf: "https://doi.org/10.18452/25694"
doi: "10.18452/25694"
date: 2022-12-04
comments: false
sharing: true
footer: true

---