---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "42"
year: "2022"
contributor: 
- "Redaktion LIBREAS"
title: "Das liest die LIBREAS, Nummer #11 (Herbst bis Winter 2022)"
pdf: "main.pdf"
date: 2022-12-03
comments: false
sharing: true
footer: true

---