---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "42"
year: "2022"
contributor: 
- Hannah Böhlke
title: "Zweitveröffentlichungsservices an deutschen Universitätsbibliotheken: Leistungsspektrum, Kategorisierung und Einflussfaktoren"
abstract: "Zweitveröffentlichungsservices sind an vielen Forschungseinrichtungen von zunehmender Bedeutung. In diesem Beitrag wird zunächst die Verbreitung der verschiedenen Dienstleistungen an Universitätsbibliotheken dargestellt und aufgezeigt, ob alle angebotenen Services über die Webseite kommuniziert werden oder ob sie nur auf Anfrage angeboten werden. Es wird außerdem die Möglichkeit einer Kategorisierung dieser Services betrachtet und Ausbaustufen zur Einordnung vorgeschlagen. Abschließend wird darauf eingegangen, inwiefern verschiedene Faktoren, wie beispielsweise die Größe der Universität, einen Einfluss auf den Ausbau des Serviceangebots haben."
pdf: "https://doi.org/10.18452/25692"
doi: "10.18452/25692"
date: 2022-12-01
comments: false
sharing: true
footer: true

---