---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "42"
year: "2022"
contributor: 
- Hannah Böhlke
title: "Zweitveröffentlichungsservices an deutschen Universitätsbibliotheken: Leistungsspektrum, Kategorisierung und Einflussfaktoren"
pdf: "main.pdf"
date: 2022-12-01
comments: false
sharing: true
footer: true

---