---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "42"
year: "2022"
contributor: 
- Ben Kaden
title: "Kolumne Bibliotheksphilokartie #2: Ein Blick nach Jüterbog"
pdf: "https://doi.org/10.18452/25695"
doi: "10.18452/25695"
date: 2022-12-03
comments: false
sharing: true
footer: true

---